"""Render STATUS.md from the census artifact, so no number is hand-typed.

This lane already caught one hand-transcribed constant that was simply wrong
(the developability clip ceiling, written as 1.32669 where the computed value is
1.3267132048600137) and one fabricated SHA-256 is on the project's defect list.
A status page is exactly where a stale or mistyped number does the most damage,
because it is the first thing a main-session agent reads.

So STATUS.md is generated. If a number here disagrees with the artifact, the
artifact wins and this script says so.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

TEMPLATE = """# STATUS — Workstream E, target-free Pareto / preference control

*Generated by `scripts/pareto_render_status.py` from
`diagnostics/pareto_tradeoff_census.json`. Do not hand-edit: regenerate.*

**Status:** `DESIGN_ONLY` for the arms and the smoke plan; `SMOKE_HELD_IN` for
the Stage 0 census.

**Branch / commit:** `{branch}` @ `{commit}` (base `a0e680d`).

**Running:** nothing. **No Modal run has been launched in this lane.**

**Held-out opened:** **NO.** `reserve_source_keys` was never read. Every
measurement uses `training_source_keys`.

## Last completed gate — the Stage 0 headroom gate

Thresholds were committed at `d206d55`, **before** the census existed. Adoption
is positional: the first pair in the predeclared order clearing all five gates.

**Adopted pair: `{adopted}`**  — positional: the FIRST pair in the predeclared
order clearing all five gates, not the best-scoring one.

| pair | Spearman rho | verdict | failed gates |
|---|---:|---|---|
{pair_rows}

### {gate_heading}

| gate | statistic | value | threshold | pass |
|---|---|---:|---|---|
{gate_rows}

### Instruments

- **I-A** (primary): the real model-gated canonical successor fiber —
  **{ia_states} decision states, mean fiber width {ia_width:.0f}**, depths 0 and 1,
  local, support only, no transition probability read.
- **I-B** (cross-check): **{ib_pairs:,} one-cut MMP pairs, {ib_states} decision
  states**, no kernel at all.

### C5 — does a 6-edit budget exhaust either axis?

Single-objective greedy rollouts at the full budget, on {reach_n} held-in sources:

{reach_rows}

## Next action

Authorize the **12-source held-in smoke** in
`modal_apps/pareto_control_app.py`. The cohort is frozen at
`diagnostics/pareto_control_cohort.json` (sha256 `{cohort_sha}`), disjoint from
the census sources. Costed in `HANDOFF.md`: ~700 kernel calls per source,
~1.4 h wall and ~$18 at `cpu=8.0`.

## Artifacts

| file | status | sha256 |
|---|---|---|
{artifact_rows}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--census", type=Path,
                        default=REPO / "diagnostics/pareto_tradeoff_census.json")
    parser.add_argument("--out", type=Path,
                        default=REPO / "docs/workstreams/pareto-control/STATUS.md")
    args = parser.parse_args()

    census = json.loads(args.census.read_text())
    adopted = census.get("adopted_pair") or "NONE — all three pairs failed"

    pair_rows = []
    for entry in census["pairs"]:
        failed = ", ".join(entry["gate"]["failed"]) or "—"
        mark = " **(adopted)**" if entry["pair"] == census.get("adopted_pair") else ""
        pair_rows.append(f"| `{entry['pair']}`{mark} | {entry['spearman_rho']:+.3f} "
                         f"| {entry['gate']['verdict']} | {failed} |")

    # If NO pair passed, show the FIRST pair in the predeclared order and say so.
    # Labelling a failing pair "the adopted pair" would misread the whole census.
    adopted_name = census.get("adopted_pair")
    chosen = next((e for e in census["pairs"] if e["pair"] == adopted_name),
                  census["pairs"][0])
    gate_heading = (f"The adopted pair `{chosen['pair']}`, gate by gate"
                    if adopted_name else
                    f"NO PAIR PASSED. First in the predeclared order, "
                    f"`{chosen['pair']}`, gate by gate")
    ia = chosen["I_A"]
    gates = chosen["gate"]["gates"]
    gate_rows = [
        f"| G1 alignment | Spearman rho | {chosen['spearman_rho']:+.3f} | "
        f"< +{census['predeclared_gate_thresholds']['G1_max_rho']:.2f} | "
        f"{'PASS' if gates['G1_alignment']['pass'] else 'FAIL'} |",
        f"| G2 local tradeoff | tradeoff-move fraction (I-A) | "
        f"{ia['tradeoff_move_fraction']:.3f} | >= "
        f"{census['predeclared_gate_thresholds']['G2_min_tradeoff_fraction']:.2f} | "
        f"{'PASS' if gates['G2_local_tradeoff']['pass'] else 'FAIL'} |",
        f"| G2 local tradeoff | states offering each direction (I-A) | "
        f"{ia['state_offers_a_up_b_down']:.3f} / {ia['state_offers_a_down_b_up']:.3f} | "
        f">= {census['predeclared_gate_thresholds']['G2_min_state_availability']:.2f} | "
        f"{'PASS' if gates['G2_local_tradeoff']['pass'] else 'FAIL'} |",
        f"| G3 no domination | max binding share | {ia['max_binding_share']:.3f} | "
        f"<= {census['predeclared_gate_thresholds']['G3_max_binding_share']:.2f} | "
        f"{'PASS' if gates['G3_no_domination']['pass'] else 'FAIL'} |",
        f"| G4 no saturation | reach fractions | "
        + " / ".join(f"{k} {v:.3f}" for k, v in gates['G4_no_saturation']
                     ['reach_fractions'].items())
        + f" | <= {census['predeclared_gate_thresholds']['G4_max_reach_fraction']:.2f} | "
          f"{'PASS' if gates['G4_no_saturation']['pass'] else 'FAIL'} |",
        f"| G5 front richness | distinct selections of 5 (I-A) | "
        f"{ia['mean_distinct_selections']:.2f} | >= "
        f"{census['predeclared_gate_thresholds']['G5_min_distinct_selections']:.1f} | "
        f"{'PASS' if gates['G5_front_richness']['pass'] else 'FAIL'} |",
        f"| G5 front richness | states where all 5 agree (I-A) | "
        f"{ia['unanimous_fraction']:.3f} | <= "
        f"{census['predeclared_gate_thresholds']['G5_max_unanimous_fraction']:.2f} | "
        f"{'PASS' if gates['G5_front_richness']['pass'] else 'FAIL'} |",
    ]

    reach = census["C5_reachability"]
    reach_rows = []
    for key in ("P", "D"):
        if key in reach:
            r = reach[key]
            reach_rows.append(
                f"- **{key}** — reach fraction {r['reach_fraction']:.3f}, median "
                f"endpoint {r['median_end']:+.3f}, median movement "
                f"{r['median_movement']:+.3f} over 6 edits.")
    if "S" in reach:
        r = reach["S"]
        reach_rows.append(
            f"- **S** — median absolute movement {r['median_abs_movement']:.4f} in "
            f"z_S units over 6 edits; **inert: {r['inert']}**. No ceiling is "
            f"reachable (`T = 1` needs zero edits), so the axis is tested for "
            f"inertness instead.")
    reach_rows.append(
        f"- Withdrawn statistic: {reach['withdrawn_statistic']}")

    cohort_path = REPO / "diagnostics/pareto_control_cohort.json"
    cohort_sha = (json.loads(cohort_path.read_text())["cohort_sha256"][:16]
                  if cohort_path.exists() else "NOT FROZEN")

    artifacts = {
        "docs/workstreams/pareto-control/PROTOCOL.md": "DESIGN_ONLY",
        "configs/pareto_control_protocol_v1.json": "DESIGN_ONLY",
        "src/compose_v4/experiments/pareto_control.py": "DESIGN_ONLY",
        "modal_apps/pareto_control_app.py": "DESIGN_ONLY (not launched)",
        "diagnostics/pareto_control_cohort.json": "DESIGN_ONLY",
        "diagnostics/pareto_tradeoff_census.json": "SMOKE_HELD_IN",
    }
    artifact_rows = []
    for path, status in artifacts.items():
        target = REPO / path
        digest = (hashlib.sha256(target.read_bytes()).hexdigest()[:16]
                  if target.exists() else "MISSING")
        artifact_rows.append(f"| `{path}` | `{status}` | `{digest}` |")

    branch = subprocess.run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=REPO,
                            capture_output=True, text=True).stdout.strip()
    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=REPO,
                            capture_output=True, text=True).stdout.strip()

    args.out.write_text(TEMPLATE.format(
        branch=branch, commit=commit, adopted=adopted,
        pair_rows="\n".join(pair_rows), gate_rows="\n".join(gate_rows),
        ia_states=census["instruments"]["I_A"]["n_states"],
        ia_width=census["instruments"]["I_A"]["mean_fiber_width"],
        ib_pairs=census["instruments"]["I_B"]["n_pairs"],
        ib_states=census["instruments"]["I_B"]["n_states"],
        reach_n=reach["n_sources"], reach_rows="\n".join(reach_rows),
        gate_heading=gate_heading,
        cohort_sha=cohort_sha, artifact_rows="\n".join(artifact_rows)))
    print(f"wrote {args.out}  (adopted pair: {adopted})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
