"""Build and seal the three canonical T4 arm contracts from ONE shared configuration.

The three contracts are produced by one function from one ``SHARED_CONTROLLER`` dict,
so they cannot drift: ``controller_identity`` is recomputed over each sealed payload
and the builder REFUSES to write anything unless all three agree. Only three fields
differ, and each is declared rather than implied:

    experts                        the arm's proposal vocabulary
    adaptive_support_expansion     an explicit boolean
    support_expansion              present iff that boolean is true

Cells are generated by ``t4_canonical_controller.canonical_cells`` from the published
seed registry, so the source molecules, the deltas and the per-cell RNG seeds are a
pure function of the benchmark inputs and are byte-identical across arms wherever a
cell appears in more than one.

Usage::

    python3 tools/build_t4_canonical_contracts.py --status draft
    python3 tools/build_t4_canonical_contracts.py --status authorized
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from compose_v4.control.docking_value import identity
from compose_v4.experiments.continuation_profile import sha256_file
from compose_v4.experiments.t4_canonical_controller import (
    ADAPTIVE_SUPPORT_EXPANSION,
    ARMS,
    EXPANSION_TRIGGER_MIN_ELIGIBLE,
    QVINA02_SHA256,
    SHARED_CONTROLLER,
    canonical_cells,
    cell_identity_digest,
    controller_identity,
    load_seeds,
)
from compose_v4.experiments.t4_matched_pilot import seal

SEEDS = "docs/GENMOL_T4_SEEDS.json"
APP = "modal_apps/t4_canonical_shared_controller_app.py"

#: Every file whose bytes can change what the controller proposes, executes, gates or
#: records. This is the CONTROL-PATH closure: the modules `expand`, the three lane
#: samplers, the zero-support fallback, the executor entry points and `Fiber.check`
#: reach, plus their direct dependencies, derived by running the real path
#: (`tools/derive_t4_canonical_closure.py`) rather than by reading import statements.
#:
#: SCOPE, stated rather than implied: the full `sys.modules` closure of one real draw
#: is ~100 modules, most of them training-side code the proposal path imports but never
#: executes. Pinning all of them would make any unrelated edit anywhere in the package
#: invalidate a run that is hours into its budget and cannot be resumed under a
#: different contract. What is pinned here is what decides what the controller does.
RUNTIME_INPUTS = (
    SEEDS,
    APP,
    "src/compose_v4/chem/molecular_graph.py",
    "src/compose_v4/chem/state.py",
    "src/compose_v4/control/intervention_closure.py",
    "src/compose_v4/control/bridge_region_law.py",
    "src/compose_v4/control/complete_region_program.py",
    "src/compose_v4/control/completion_law_contract.py",
    "src/compose_v4/control/docking_value.py",
    "src/compose_v4/control/dynamic_program_synthesis.py",
    "src/compose_v4/control/fiber_control.py",
    "src/compose_v4/gates/med_chem_gate.py",
    "src/compose_v4/control/progressive_structured_sampler.py",
    "src/compose_v4/control/queryable_fiber.py",
    "src/compose_v4/control/region_law_contract.py",
    "src/compose_v4/control/replace_completion_law.py",
    "src/compose_v4/control/structural_subgoal.py",
    "src/compose_v4/control/structural_subgoal_policy.py",
    "src/compose_v4/control/structural_subgoal_realizer.py",
    "src/compose_v4/control/zero_support_fallback.py",
    "src/compose_v4/experiments/t4_canonical_controller.py",
    "src/compose_v4/experiments/t4_docking_adapter.py",
    "src/compose_v4/experiments/t4_fiber_campaign.py",
    "src/compose_v4/experiments/t4_integrated_route_fiber.py",
    "src/compose_v4/experiments/t4_support_expansion.py",
    "src/compose_v4/control/adaptive_program_optimizer.py",
    "src/compose_v4/control/current_state_edits.py",
    "src/compose_v4/control/dependency_region_program.py",
    "src/compose_v4/control/dynamic_program_synthesis_v1.py",
    "src/compose_v4/control/edit_program.py",
    "src/compose_v4/control/edit_program_graph.py",
    "src/compose_v4/control/ring_program.py",
    "src/compose_v4/control/structural_subgoal_components.py",
    "src/compose_v4/experiments/whole_ring_plan.py",
    "src/compose_v4/rewrite/action_codec_v4.py",
    "src/compose_v4/rewrite/trace_shard.py",
    "src/compose_v4/rewrite/kernel.py",
    "src/compose_v4/rewrite/operators.py",
)

TARGET = {arm: f"configs/t4_canonical_shared_controller_{arm.lower()}_v1.json" for arm in ARMS}

CLAIM_BOUNDARY = (
    "One frozen controller configuration, identical on every cell of every arm, over the "
    "15 published T4 held-target seeds. Target molecule, receptor and delta are the only "
    "per-cell inputs; no cell-name or target-name conditional exists anywhere in the "
    "runtime (asserted structurally by t4_canonical_controller.assert_no_target_name_routing). "
    "The coordinated lanes are the task-independent progressive and anchored-replacement "
    "samplers; the route-distilled expert is DELIBERATELY EXCLUDED because every available "
    "checkpoint is a leave-one-target-out fit over the benchmark's own winner routes. "
    "Docking is not reproducible across runs (obabel --gen3D is unseeded), so only "
    "within-run comparisons between arms are sound; per-cell margins against any earlier "
    "panel are not. Historical rescue and support-expansion scores are NOT spliced into "
    "this table."
)

SCIENTIFIC_PROBLEM = (
    "Does one frozen controller -- local executable programs, coordinated structural "
    "programs, and state-dependent adaptive support expansion inside one validity-closed "
    "molecular process -- work across the whole T4 panel without per-target adaptation, "
    "and what does each component contribute?"
)


def _git_revision() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
    except (OSError, subprocess.SubprocessError):
        return "unknown"


def build_arm(arm: str, *, status: str, seeds: list[dict]) -> dict:
    spec = ARMS[arm]
    cells = canonical_cells(seeds, spec["deltas"])
    payload: dict = {
        "schema_version": "t4_canonical_shared_controller_contract_v1",
        "status": status,
        "arm": spec["arm"],
        "arm_name": spec["arm_name"],
        "arm_isolates": spec["isolates"],
        "scientific_problem": SCIENTIFIC_PROBLEM,
        "primary_model_output": (
            "a docking-feedback-adapted selection over complete executable COMPOSE "
            "programs drawn from the arm's declared proposal vocabulary"
        ),
        "prospective_primary": "C",
        "cells": cells,
        "cell_identity_sha256": cell_identity_digest(cells),
        "deltas": [float(value) for value in spec["deltas"]],
        "experts": list(spec["experts"]),
        "adaptive_support_expansion": bool(spec["adaptive_support_expansion"]),
        "expansion_trigger_min_eligible": (
            EXPANSION_TRIGGER_MIN_ELIGIBLE if spec["adaptive_support_expansion"] else 0
        ),
        "total_charged_call_ceiling": len(cells) * SHARED_CONTROLLER["charged_calls_per_cell"],
        "evaluator_sha256": {"qvina02": QVINA02_SHA256},
        "round_lock_policy": {
            "publish_complete_candidate_pool_before_docking": True,
            "no_backfill": True,
            "no_candidate_replacement": True,
            "automatic_docking_retries": 0,
            "persist_after_every_round_including_root": True,
        },
        "claim_boundary": CLAIM_BOUNDARY,
        "code_revision": _git_revision(),
    }
    payload.update({key: value for key, value in SHARED_CONTROLLER.items()})
    if spec["adaptive_support_expansion"]:
        payload["support_expansion"] = dict(ADAPTIVE_SUPPORT_EXPANSION)
    payload["runtime_inputs_sha256"] = {
        relative: sha256_file(ROOT / relative) for relative in sorted(RUNTIME_INPUTS)
    }
    return payload


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--status", choices=("draft", "authorized"), required=True)
    args = parser.parse_args()
    status = {
        "draft": "DRAFT_NOT_AUTHORIZED",
        "authorized": "AUTHORIZED_T4_CANONICAL_SHARED_CONTROLLER_15000_CALLS",
    }[args.status]

    seeds = load_seeds(ROOT / SEEDS)
    payloads = {arm: build_arm(arm, status=status, seeds=seeds) for arm in sorted(ARMS)}

    # The three arms MUST agree on the shared controller. A builder that can emit three
    # contracts which merely look alike is not evidence that one controller ran.
    identities = {arm: controller_identity(payload) for arm, payload in payloads.items()}
    if len(set(identities.values())) != 1:
        raise SystemExit(f"arms disagree on the shared controller: {identities}")

    # Cells that appear in more than one arm must be byte-identical inputs.
    by_cell: dict[str, dict] = {}
    for arm, payload in payloads.items():
        for cell in payload["cells"]:
            previous = by_cell.setdefault(cell["cell"], cell)
            if previous != cell:
                raise SystemExit(f"cell {cell['cell']!r} differs between arms")

    total = sum(payload["total_charged_call_ceiling"] for payload in payloads.values())
    report = {
        "controller_identity_sha256": next(iter(set(identities.values()))),
        "total_charged_call_ceiling": total,
        "arms": {},
    }
    for arm in sorted(payloads):
        payload = payloads[arm]
        destination = ROOT / TARGET[arm]
        seal(destination, payload)
        report["arms"][arm] = {
            "path": TARGET[arm],
            "payload_sha256": identity(payload),
            "file_sha256": sha256_file(destination),
            "cells": len(payload["cells"]),
            "experts": payload["experts"],
            "adaptive": payload["adaptive_support_expansion"],
            "ceiling": payload["total_charged_call_ceiling"],
        }
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
